name: easyrpg-player
base: core18
adopt-info: easyrpg-player
summary: easyrpg-player
description: |
    easyRPG Player
confinement: strict
grade: stable

apps:
  easyrpg-player:
    command: desktop-launch $SNAP/usr/bin/easyrpg-player
    plugs:
      - x11
      - wayland
      - unity7
      - opengl
      - audio-playback
      - joystick
      - home

    environment:
      XDG_DATA_HOME: $SNAP_USER_COMMON/
      DBUS_FATAL_WARNINGS: 0

parts:
  liblcf:
    plugin: autotools
    source: https://github.com/EasyRPG/liblcf
    source-type: git
    configflags:
      - --prefix=/usr
    build-packages:
      - libexpat1-dev
      - libicu-dev
      - icu-devtools

  easyrpg-player:   
    plugin: autotools
    after: [fmtlib,liblcf,desktop-glib-only]
    source: https://github.com/EasyRPG/Player
    source-type: git
    configflags:
      - --prefix=/usr
    override-build: |
      snapcraftctl set-version "$(git -C $SNAPCRAFT_PART_SRC describe --tags)"
      snapcraftctl build

    build-packages:
      - libfreetype6-dev
      - libopusfile-dev
      - libpixman-1-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libsndfile1-dev
      - libspeex-dev
      - libvorbis-dev
      - libwildmidi-dev
      - libxmp-dev

    stage-packages:
      - libfreetype6
      - libstdc++6
      - libicu60
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libopusfile0
      - libpixman-1-0
      - libpng16-16
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libsndfile1
      - libspeex1
      - libvorbis0a
      - libwayland-egl1-mesa
      - libwildmidi2
      - libxmp4
      - locales-all
      - mpg123

  fmtlib:
    plugin: cmake
    source: https://github.com/fmtlib/fmt
    source-type: git

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
