name: easyrpg-player
base: core20
adopt-info: easyrpg-player
summary: easyrpg-player
description: |
    easyRPG Player
confinement: strict
grade: stable

apps:
  easyrpg-player:
    command: bin/desktop-launch $SNAP/usr/bin/easyrpg-player
    plugs:
      - x11
      - wayland
      - unity7
      - opengl
      - audio-playback
      - joystick
      - home

    environment:
      XDG_DATA_HOME: $SNAP_USER_COMMON/
      DBUS_FATAL_WARNINGS: 0

layout:
  /etc/wildmidi:
    bind: $SNAP/etc/wildmidi
  /usr/share/midi/freepats:
    bind: $SNAP/usr/share/midi/freepats

parts:
  liblcf:
    plugin: autotools
    source: https://github.com/EasyRPG/liblcf
    source-type: git
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - libexpat1-dev
      - libicu-dev
      - icu-devtools
    stage-packages:
      - libicu66

  easyrpg-player:   
    plugin: autotools
    after: [libwildmidi,liblcf,desktop-glib-only]
    source: https://github.com/EasyRPG/Player
    source-type: git
    autotools-configure-parameters:
      - --prefix=/usr
    override-build: |
      snapcraftctl set-version "$(git -C $SNAPCRAFT_PART_SRC describe --tags)"
      snapcraftctl build

    build-packages:
      - libfmt-dev
      - libfreetype6-dev
      - libharfbuzz-dev
      - libmpg123-dev
      - libopusfile-dev
      - libpixman-1-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libsndfile1-dev
      - libspeexdsp-dev
      - libvorbis-dev
      - libxmp-dev

    stage-packages:
      - freepats
      - libfreetype6
      - libharfbuzz0b
      - libmpg123-dev
      - libstdc++6
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libopusfile0
      - libpixman-1-0
      - libpng16-16
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libsndfile1
      - libspeexdsp1
      - libvorbis0a
      - libwayland-egl1-mesa
      - libwildmidi-config
      - libxmp4
      - locales-all

  libwildmidi:
    plugin: cmake
    source: https://github.com/Mindwerks/wildmidi
    source-type: git
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SHARED_LIBS=OFF
      - -DWANT_PLAYER=ON
      - -DWANT_STATIC=ON
 
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
